---
name: elasticsearch
director_uuid: 24ffba31-13c5-415a-a4a5-54cccff2669d 

release:
  name: elasticsearch
  version: latest

compilation:
  workers: 2
  network: default
  cloud_properties:
    instance_type: m3.medium
    availability_zone: eu-west-1a

# this section describes how updates are handled
update:
  canaries: 1
  canary_watch_time: 30000
  update_watch_time: 30000
  max_in_flight: 1
  max_errors: 1

networks:

- name: default
  type: manual
  subnets:
  - range: 10.10.1.0/24
    gateway: 10.10.1.1
    reserved: [ '10.10.1.2 - 10.10.1.10' ]
    static:   [ '10.10.1.11 - 10.10.1.20' ]
    cloud_properties:
      subnet: subnet-e9ae2bb0 

resource_pools:

- name: infrastructure
  network: default
  size: 4
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent 
    version: latest
  cloud_properties:
    instance_type: m3.medium
    availability_zone: eu-west-1a

jobs:

- name: elasticsearch
  template: elasticsearch
  persistent_disk: 2048
  instances: 2
  resource_pool: infrastructure 
  networks:
  - name: default
    static_ips: &ping_hosts
    - 10.10.1.11
    - 10.10.1.12

- name: elasticsearch-dynamic
  template: elasticsearch
  persistent_disk: 2048
  instances: 2
  resource_pool: infrastructure 
  networks:
  - name: default

properties:

  elasticsearch:
    cluster: my-awesome-cluster
    ping_hosts: *ping_hosts
